### ISSUE TITLE
No error when the bot executable is not found

### ISSUE THREAD

**Issue by ddebree** [EntelectChallenge/2018-TowerDefence#57]
When the runner tries to run the sample java bot, there is no visible error when it fails to find the actual executable jar file. This makes it really hard to realize the actual issue. 
For example, with the change in version number, the java jar file produced by the build is `java-sample-bot-1.1-SNAPSHOT-jar-with-dependencies.jar` instead of the `java-sample-bot-1.0-SNAPSHOT-jar-with-dependencies.jar`. The bot.json file still pointed at the old version number.
When I ran the `run.bat` command there was no indication from the runner that it was failing to locate the defined jar file. Instead it just complains that no command file is present. I would have expected a big error message saying the jar file is missing or at least that the java command it must be running internally failed.

**Comment by Blaarkies** [comment]
Now checks that the bot file exists before adding the player to the roster. Throws a specific exception for end-user:
"Could not find JAVA bot file for John Doe(James)"
